"""Public integration adapters for sibling systems."""

from .model_adapter import (
    ModelAdapterError,
    ModelFailureCode,
    ModelIllegalEnumError,
    ModelProbabilityViolationError,
    ModelProviderError,
    ModelRequest,
    ModelResponse,
    ModelResponseFormatError,
    ModelResponseSchemaError,
    ModelTimeoutError,
    PAModelAdapter,
    PAChatClientAdapter,
    PAModelClient,
    StrictModelOutput,
    StructuredModelClient,
)
from .pa_link import (
    BridgeContext,
    PAStage2Input,
    PAStage2Bridge,
    PAStage2Link,
    PAStage2Status,
    PAWorkspaceState,
    PADecisionPoint,
    PALinkMode,
    Stage2Completion,
    build_product_tabs,
    SecondOrderInput,
    sanitize_pa_payload,
)
from .t1_trade_gate import (
    IndependentT1TradeGate,
    IntegratedT1GateResult,
    IntegratedT1GateStatus,
    T1TradeGate,
    T1TradeGateResult,
)
from .production_orchestrator import (
    ProductionAnalysisResult,
    ProductionOrchestrator,
    ProductionRunState,
    ProductionRunStatus,
    build_production_orchestrator,
)
from .pa_embedded_service import PAEmbeddedService, normalize_pa_payload
from .pa_market_adapter import PAMarketDataAdapter
from .progress import ProgressEvent, ProgressSink
from .labeler_status import (
    LabelerStatus,
    LabelerStatusTracker,
    LoadState,
    RunState,
    StatusCallback,
)
from .sector_analysis_service import (
    CapitalFlowSnapshot,
    DragonTigerSnapshot,
    LimitPoolSnapshot,
    SectorAnalysisBundle,
    SectorAnalysisService,
)

__all__ = [
    "ModelAdapterError",
    "ModelFailureCode",
    "ModelIllegalEnumError",
    "ModelProbabilityViolationError",
    "ModelProviderError",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseFormatError",
    "ModelResponseSchemaError",
    "ModelTimeoutError",
    "PAModelAdapter",
    "PAChatClientAdapter",
    "PAModelClient",
    "StrictModelOutput",
    "StructuredModelClient",
    "BridgeContext",
    "PAStage2Input",
    "PAStage2Bridge",
    "PAStage2Link",
    "PAStage2Status",
    "PAWorkspaceState",
    "PADecisionPoint",
    "PALinkMode",
    "Stage2Completion",
    "build_product_tabs",
    "SecondOrderInput",
    "sanitize_pa_payload",
    "IndependentT1TradeGate",
    "IntegratedT1GateResult",
    "IntegratedT1GateStatus",
    "T1TradeGate",
    "T1TradeGateResult",
    "ProductionAnalysisResult",
    "ProductionOrchestrator",
    "ProductionRunState",
    "ProductionRunStatus",
    "build_production_orchestrator",
    "PAEmbeddedService",
    "normalize_pa_payload",
    "PAMarketDataAdapter",
    "ProgressEvent",
    "ProgressSink",
    "LabelerStatus",
    "LabelerStatusTracker",
    "LoadState",
    "RunState",
    "StatusCallback",
    "CapitalFlowSnapshot",
    "DragonTigerSnapshot",
    "LimitPoolSnapshot",
    "SectorAnalysisBundle",
    "SectorAnalysisService",
]
